defaults: &defaults
  working_directory: /go/src/github.com/write-blog-every-week/write-blog-every-week-remind
  docker:
    - image: circleci/golang:latest
  environment:
    - GOPATH: /go
    - SRC_PATH: /go/src/github.com/write-blog-every-week/write-blog-every-week-remind

branches: &branches
  only:
    - master
    - circleci
    - /pull/.*

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Get dependency packages
          command: go get ./...
      - persist_to_workspace:
          root: /go/
          paths:
            - bin/*
            - src/*
            - pkg/*

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go/
      # specify any bash command here prefixed with `run: `
      - run: go get github.com/pierrre/gotestcover
      - run: gotestcover -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            branches:
              <<: *branches
      - test:
          requires:
            - build
          filters:
            branches:
              <<: *branches
